### PR TITLE
Support slash commands

### LINKED ISSUE #7: [feature] Support slash commands
Discord allows bots to register `/commands` which can provide native hints and tab-completion, hints and tab-completion of subcommands, and rich replies.

It will take some work to rebase on [interactions](https://interactionspy.readthedocs.io/en/latest/quickstart.html), but the user experience should be worth it.

### PR DESCRIPTION
**Pull request by xPMo**
Putting this out in the open while I work through it. We are rebasing on `pycord`, which is a fork of `discord.py`, it seems to be better supported. Closes #7.

### CODE REVIEW

**Comment by xPMo** [comment]
Docs for the interested: https://guide.pycord.dev/getting-started/more-features

**Comment by xPMo** [comment]
I think this is ready now. I still want to change `/char` to use embeds, but I'll save that for a future PR.

I've also embedded the input into the output for `/roll`, ~~because otherwise you can't tell what dice the user rolled, and the user could easily use `1d5 +6` to force a die to be a 6 and ensure the other isn't.~~ **(EDIT: Actually, clicking on the "User used [/roll](/roll)" link shows the dice argument. I still prefer embedding it.)** I'll probably switch this to an embed as well. Again, future PR.

**Comment by xPMo** [comment]
Note that there are a few stack changes:
- Switched from discord to py-cord (Rationale: py-cord supports slash commands)
- Added BeautifulSoup and html2text as required packages (Rationale: extracting sooth card details)
- Switched base image from `python:3.9-bullseye` to `python:alpine` (Rationale: much smaller image, better performance on newer Python)
- Re-ordered Dockerfile (Rationale: much faster rebuilds if only `theMoth.py` has changed)

**Comment by v01dlight** [comment]
This is awesome; you're the best!

**Pull request merged**
