### PR TITLE
Update Moth bot with Invisible Sun style rolling.

### PR DESCRIPTION
**Pull request by Baconaetor**
Love "The Moth" bot, but found it was just rolling regular dice instead of the Invisible Sun style. The changes detailed below customize it to have this style of rolling. 

Changed to support the standard Invisible Sun rolling style. When just told to roll, it will return a random roll from 0-9. When told to roll with a number, will roll a "mundane die" with results 0-9, then roll "magic die" until the total number of dice is reached. This makes it easier to see and track flux, and prevents the momentary hype of seeing a 10 before realizing it's actually a 0. Regular dice rolling functionality is maintained using the unchanged syntax.

### CODE REVIEW

**Comment by v01dlight** [comment]
Hi!

I love the idea and greatly appreciate the interest in the project! I created a beta version of the bot in a private server to test your implementation of IS dice and noticed that it breaks the standard dice rolling a bit. `?roll d20` will return nothing because it's interpreting it as a single argument and thus trying to apply the IS dice logic which just breaks and throws an error behind the scenes. This can be mitigated by formatting a simple d20 roll as `?roll d20 +0` so that it has two arguments but... that's a bit clunky. Especially because my home game is d20 based!

The `if len(args) < 2:` line (#39) could be changed to fix this bug and support cases where you want to roll non IS dice without a modifier, but personally I think the better solution would be to simply split the IS dice feature into another command, like `?roll-is`.

I'm gonna hold off on merging this for now but if you want to take another pass on it feel free and I can test it now that I have a beta bot set up. If not I may get around to fixing it eventually.

**Comment by v01dlight** [comment]
image

**Comment by v01dlight** [comment]
@Baconaetor
If you do end up reworking this implementation, I also recommend changing the format of IS roll output to something a bit cleaner looking, maybe similar to how the Black Cube bot displays rolls:

image

**Comment by Baconaetor** [comment]
Damn! Sorry, I'm not sure how I missed this, yeah I'll go back and fix that.

Hmm, I'm not sure I like how the Black Cube does it. This was my first implementation so I left it a little open ended in chase I ever had the time to go back and build more. Anyway, the idea behind the format was to make it easier to track flux, with magical die and whatnot. I'll look that over too though and see if there's a better way.

**Comment by Baconaetor** [comment]
Ok, I fixed the main issue and cleaned up the results a bit. I also added one of the features I originally wanted to add which is magical flux tracking. 

Let me know what you think!

**Comment by v01dlight** [comment]
Merged! I did some testing first and it looks good. I like the format that splits out the mundane die from the magic dice.

**Comment by v01dlight** [comment]
I did some tweaking and added the new code to the server, so you should be able to use the new roll command in Discord now. Thanks again for your interest and work on this!

**Comment by Baconaetor** [comment]
Awesome, thank you! I was so excited to show this off to my group!

**Pull request merged**
